Traceback (most recent call last):
  File "simple_server.py", line 49, in <module>
    start_p()
  File "simple_server.py", line 46, in start_p
    run(PrimaryHTTPRequestHandler,d['primary'],int(d['port']))
  File "simple_server.py", line 27, in run
    httpd = server_class(server_address,handler_class)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 443, in __init__
    self.server_bind()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 457, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
Traceback (most recent call last):
  File "simple_server.py", line 49, in <module>
    start_p()
  File "simple_server.py", line 46, in start_p
    run(PrimaryHTTPRequestHandler,d['primary'],int(d['port']))
  File "simple_server.py", line 27, in run
    httpd = server_class(server_address,handler_class)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 443, in __init__
    self.server_bind()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 457, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
